version: '3.8'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: chat-api-container
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "8080:8080"
      - "443:443"
    depends_on:
      - postgres
    restart: always
    volumes:
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys

  postgres:
    image: postgres:16
    container_name: chat-api-postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "Application@2025"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"

volumes:
  dataprotection-keys:
  mssql-data:
    driver: local

networks:
  production:
    driver: bridge