version: '3.8'
services:
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      DbServer: "mssql-server"
      DbPort: "1433"
      DbUser: "SA"
      Password: "serverApp@2025"
      Database: "CoreDb"
    ports:
      - "8080:8080"
      - "443:443"
    depends_on:
      - mssql-server
    restart: always
    volumes:
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys

  mssql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "serverApp@2025"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql/data
    restart: always

volumes:
  dataprotection-keys:
  mssql-data:
    driver: local

networks:
  production:
    driver: bridge