version: '3.8'
services:
  chat-api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: chat-api-container
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      DbServer: ${DbServer}
      DbPort: ${DbPort}
      Database: ${Database}
      DbTenant: ${DbTenant}
      DbUser: ${DbUser}
      DbPassword: ${DbPassword}
    ports:
      - "8080:8080"
      - "443:443"
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./keys:/app/keys

  postgres:
    image: postgres:16
    container_name: chat-api-postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "Application@2025"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"

networks:
  production:
    driver: bridge