name: Build and Deploy Chat API Docker Image

on:
  push:
    branches:
      - 'main'
      - 'develop'
    tags:
      - 'v*'

jobs:
  test:
    name: Run Tests and Coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ChatApi/ChatApi.csproj

    - name: Run Tests
      run: dotnet test ChatApi.Tests/ChatApi.Tests.csproj --no-restore --verbosity normal

  build:
    name: Build Docker Image
    needs: test
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v2

    - name: Notify Discord (Build Started)
      run: |
        curl -H "Content-Type: application/json" \
        -X POST \
        -d '{"username": "Bot Docker", "content": "🚀 **Build da imagem Chat API iniciado!**\nRepositório: `${{ github.repository }}`\nBranch/Tag: `${{ github.ref_name }}`"}' \
        ${{ secrets.DISCORD_WEBHOOK_URL }} || true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image (branch main)
      if: github.ref == 'refs/heads/main'
      run: |
        docker build --platform=linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/chat-api:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/chat-api:latest

    - name: Build and push Docker image (branch develop)
      if: github.ref == 'refs/heads/develop'
      run: |
        docker build --platform=linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/chat-api:develop .
        docker push ${{ secrets.DOCKER_USERNAME }}/chat-api:develop

    - name: Build and push Docker image (tagged release)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        docker build --platform=linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/chat-api:${{ github.ref_name }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/chat-api:${{ github.ref_name }}

  report-status:
    name: Report Build Status
    needs: build
    environment: production
    runs-on: ubuntu-latest

    steps:
    - name: Notify Discord (Success)
      if: success()
      run: |
        curl -H "Content-Type: application/json" \
        -X POST \
        -d '{"username": "Bot Docker", "content": "✅ **Chat API Docker Image Build Sucesso!**\nBranch/Tag: `${{ github.ref_name }}`"}' \
        ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Notify Discord (Failure)
      if: failure()
      run: |
        curl -H "Content-Type: application/json" \
        -X POST \
        -d '{"username": "Bot Docker", "content": "❌ **Falha ao buildar a imagem do Chat API!**\nBranch/Tag: `${{ github.ref_name }}`"}' \
        ${{ secrets.DISCORD_WEBHOOK_URL }}